package com.jade.api;

public enum ErrorCode {
    INVALID_COMMAND,
    UNKNOWN_APP,
    CANCELLED,
    UNSUPPORTED_PLATFORM,
    MISSING_DEPENDENCY,
    ACCESS_DENIED,
    IO_FAILURE,
    TARGET_EXISTS,
    CONFIRMATION_REQUIRED,
    CONFIRMATION_DENIED,
    DATABASE_FAILURE,
    SERVICE_FAILURE
}
